# Changes here will be overwritten by Copier
_commit: 8265bae
_src_path: gh:browniebroke/pypackage-template
add_me_as_contributor: false
copyright_year: '2024'
documentation: true
email: sungshic@hotmail.com
full_name: Sunny Park
github_username: sungshic
has_cli: false
initial_commit: false
is_django_package: false
open_source_license: MIT
package_name: gsap
project_name: Genome Sequence Assembly Pipeline
project_short_description: 'NGS devices generate short sequence reads collated together
    into raw unassembled

    sequence data formats, such as FASTQ. There are a series of steps involved in

    converting the raw data into some form ready to be consumed by other high-

    level bioinformatic analyses. This Python package is a software pipeline implementation
    that automates

    the assembly and the annotation of NGS sequence data from short sequence reads.
    The pipeline also performs

    variant analysis to annotate the assembled sequence about any SNPs and INDELs
    with respect to a reference genome of choice.'
project_slug: gsap
run_poetry_install: false
setup_github: false
setup_pre_commit: false

