services:
  gsap:
    image: gsap
    container_name: gsap_v1.0
    build:
      context: .
      dockerfile: Dockerfile
      target: gsap
    platform: linux/x86_64
    volumes:
      - ./tests/data_input:/gsap/tests/data/data_input
      - ./tests/data_output:/gsap/tests/data/data_output
